spring.application.name=ApiLojaDeVerdadeDaviAliagaSigma

spring.datasource.url=jdbc:postgresql://pg-373f102-germinare-e0c2.h.aivencloud.com:12558/daddb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_rlMk8E04Lsf466zjLa-
spring.datasource.driver-class-name=org.postgresql.Driver