spring.application.name=ApiLojaDeVerdadeDaviAliagaSigma

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://pg-373f102-germinare-e0c2.h.aivencloud.com:12558/daddb
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_rlMk8E04Lsf466zjLa-