### Inserir usuário
POST http://localhost:8080/produto
Content-Type: application/json

{
  "nome": "Tênis de Corrida",
  "categoria": "Calçados",
  "descricao": "Tênis super confortável para corrida",
  "preco": 299.90,
  "estoque": 15,
  "vendedorId": 1
}

